### ISSUE TITLE
Understanding comparison plots between PE-lib and an assembly

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#103]
Hi Daniel,
  I went ahead at least with comparing a single paired-end dataset to three of my assemblies aiming to figure out if the one based on k-mer `160` is just inflated due to redundancy or if it is indeed more complete compared to `k144` and `k128` attempts. Here  are the figures.

![pe2016_vs_assembly_k128-main mx spectra-cn](https://user-images.githubusercontent.com/3297852/39621687-e8a747a0-4f8f-11e8-9a77-fd3231bec2b8.png)

![pe2016_vs_assembly_k144-main mx spectra-cn](https://user-images.githubusercontent.com/3297852/39621692-ec571894-4f8f-11e8-838b-f1b3f35a3fe1.png)

![pe2016_vs_assembly_k160-main mx spectra-cn](https://user-images.githubusercontent.com/3297852/39621694-efa44512-4f8f-11e8-8272-c456b04a755e.png)

They appear to me quite same. How would you answer this question? Do you need the *.stats files?

Would it be easy for you to make a figure where k-mers of one or even two assemblies are subtracted from the third? I would omit k-mers appearing in `k128` and `k144` from those in `k160`.

Or, shal I run `kat comp` on the three assemblies directly? That I did not try yet, true.

**Comment by bjclavijo** [comment]
Sorry about this being unanswered for a whole year! Probably this is too late an answer now, but anyway... The solution we have for now for this case is not ideal, but a new tool that we are creating will help with this.

For this specific case, yes I would recommend you compare assemblies to each other and check counts of k-mers reported as not in one or the other. The spectra in these images look almost exactly the same to the naked eye at least, with the first one having an almost unnoticeable extra amount of true content included, whilst having again a very marginal amount of erroneous duplications and triplications solved. I noted this by literally opening the images full-size in a big screen and switching between them. If you open the .mx file the numbers will tell you more, hopefully.

Since this is heterozygous sample and the difference seems to be in heterozygosity resolution, and all of them seem to be recovering a haplotype-and-then-some, it is hard to tell from this analysis only which assembly is best with the very small differences.

I will close the issue because I doubt you will want to continue with this and you probably solved this otherwise, sorry about the terrible response time.

If you have any question and we fail to give you an answer timely, do write to my Earlham.ac.uk account, my username is bernardo.clavijo there.

Best,

bj
