### ISSUE TITLE
Error reading input files in kat comp 

### ISSUE THREAD

**Issue by fmaguire** [TGAC/KAT#11]
Cloned repo, and compiled as per usual, all tests pass except the swig bindings.

GCC - 4.8.2-19ubuntu1
Boost version- 1.54.0.1ubuntu1
Jellyfish version- 1.1.10

Generated jellyfish hashes fine using the standard commands  

    jellyfish count -t 64 - m31 -C -s 10000000000 -o q30a1.jf31  q30a1.fq
    jellyfish count -t 64 - m31 -C -s 10000000000 -o q30a2.jf31  q30a2.fq

But when I try to run kat comp I'm running into errors to do with reading the inputs in the option parsing (I've tried both abspaths and relpaths as well as removing any possible weird filename characters like multiple periods)

    $ kat comp q30a1.jf31_0 q30a2.jf31_0

    Kmer Analysis Toolkit (KAT) V2.0.5
  
    Running KAT in COMP mode
    ------------------------

    KAT COMP completed.
    Total runtime: 0.0s

    input_handler.cc(59): Throw in function void kat::InputHandler::validateInput()
    Dynamic exception type: boost::exception_detail::clone_impl<kat::JellyfishException>
    std::exception::what: std::exception
    [kat::JellyfishError*] = Could not find input file at: ; please check the path and try again.
    Kmer Analysis Toolkit (KAT) V2.0.5

Interestingly if I provide a filepath that doesn't exist the error message correctly outputs the filepath instead of leaving it blank. 

    $ kat comp foo bar

    Kmer Analysis Toolkit (KAT) V2.0.5
  
    Running KAT in COMP mode
    ------------------------

    KAT COMP completed.
    Total runtime: 0.0s

    input_handler.cc(59): Throw in function void kat::InputHandler::validateInput()
    Dynamic exception type: boost::exception_detail::clone_impl<kat::JellyfishException>
    std::exception::what: std::exception
    [kat::JellyfishError*] = Could not find input file at: foo; please check the path and try again.

Any idea what my issue is? Something with bfs::path?

**Comment by maplesond** [comment]
The new version of KAT uses jellyfish 2.2, so you will now need to uses hashes generated by this version of jellyfish.   However, this is now built into KAT, so you don't need to provide it as an external dependency.  KAT also now has a much tighter integration with jellyfish and has it's own kmer counting routine, which saves you time and disk space by not having to use jellyfish hashes as input.  The recommended approach now is to provide your fastq or fasta files directly to KAT and it will do the work for you.  You still need to specify whether you want to count kmers canonically and how big the initial hash should be though.  This approach is actually faster than using the jellyfish hashes, and the entire KAT analysis should run faster than it would have taken you to run "jellyfish count".  There's not really a reason to uses hashes as input anymore, unless you want to apply filters, or some other advanced option when counting.

I suspect this issue is at the root of your problems.  I'll also update the README file so it's up to date for the next version.

Hope this helps.

**Comment by fmaguire** [comment]
Good to know! I'll just use fq files directly in future.

Unfortunately I'm still getting the same issue with a pair of fastq instead of hashes.  Didn't pass any flags to configure
    $ kat comp a.fq b.fq

    Kmer Analysis Toolkit (KAT) V2.0.5

    Running KAT in COMP mode
    ------------------------

    KAT COMP completed.
    Total runtime: 0.0s

    input_handler.cc(59): Throw in function void kat::InputHandler::validateInput()
    Dynamic exception type: boost::exception_detail::clone_impl<kat::JellyfishException>
    std::exception::what: std::exception
    [kat::JellyfishError*] = Could not find input file at: ; please check the path and try again.

So something seems to be going strange in the input parsing before its getting to actually doing anything with the inputs.

Tried compiling from the last release (2.0.4) instead of cloned master and it worked.  After a bit of playing around I found the latest version would work if 3 input files were provided into of just 2.

So it looks like the fix of the "segfaulting when missing input" bug in 58b920d3 has made using a 3rd input_file non-optional.

If input_3 is not supplied ```kat comp``` will still try to validate it and error out when it doesn't exist.  Whereas before 58b920d3 the check of input_3 was probably just silently failing but not causing any issues during main execution (the segfaulting) as long as input_1 and input_2 were provided.

I've submitted a PR of one possible fix but you'll probably have a better way to do it as I'm a complete C++ novice!
