### ISSUE TITLE
interpreting a reads-assembly comparison

### ISSUE THREAD

**Issue by dcopetti** [TGAC/KAT#111]
hello,

I need some guidance in interpreting the results of my reads-assembly comparison:
I run
`kat comp -o PE700-Rab1 -t 10 reads_R2_001.fastq assembly.fa`
and then 
`kat plot spectra-cn -o PE700-Rab1-main_spectra2.png -x 150 PE700-Rab1-main.mx`
and the plot I get is this
![pe700-rab1-main_spectra2](https://user-images.githubusercontent.com/13842014/44215870-dfa14800-a173-11e8-8a72-a90586123938.png)

My organism is highly heterozygous, in fact the raw reads produce a k-mer gureve like this (different amount than the one used with KAT):
![image](https://user-images.githubusercontent.com/13842014/44216005-2ee77880-a174-11e8-995a-5bedec1f56f2.png)
the peak at ~40 is the het peak.
assembly is mostly diploid, and upon aligning PE reads, the coverage distribution looks like this:
![image](https://user-images.githubusercontent.com/13842014/44216047-4b83b080-a174-11e8-986c-159d476e267d.png)
(the input was ~115x of reads, if counting the genome size as haploid)

So looking at the spectra-cn output, my interpretation is: there are lots of reads present once in the assembly (good), a few twice (for the het, that is homozygous regions assembled twice,orange) and a good amount of reads not assembled (black).
Is that right? Is the analysis done right? (shall I use a larger kmer? more reads? but I run out of memory - it is ~5 Gb 2n genome) Are other plots going to tell me something more?
My main point is to provide evidence that the assembly is complete and diploid. Quantification of the orange/red, and black areas would be great too.
Thanks,

Dario

**Comment by gonzalogacc** [comment]
Hi Dario.
Some quick comments.

```
So looking at the spectra-cn output, my interpretation is: there are lots of reads present once in the assembly (good), a few twice (for the het, that is homozygous regions assembled twice,orange) and a good amount of reads not assembled (black).
```
This is mostly right but the colours indicate copy number in the assembly not in the reads, so red kmers are once in the genome, orange kmers are twice in the genome an so on. Black kmers that are not present in the genome, the copy frequency in the reads is the position in the x axis.

```
Is that right?  Is the analysis done right? Are other plots going to tell me something more?
```
Except for this kmer/reads confusion the analysis is correct in my opinion. I don't think you need any other kat plot to qc the assembly. There is more information you can extract from that plot alone ie. duplications at the top of the first peak, no invented kmers, etc.

```
more reads? but I run out of memory - it is ~5 Gb 2n genome
```
I would try to add coverage to get a better definition of the peaks but if you are memory constrained that can be a problem. Usually if i need to subsample y use R1 instead of R2 because that gives a clearer shape because of the better quality. 
You can fine tune memory usage setting the hash table size `-H` and `-I` and disabling the hash growth ` --disable_hash_grow`

```
shall I use a larger kmer?
```
I typically user k=31, kat default is 27, usually that doesn't make a lot of difference. 
 
```
My main point is to provide evidence that the assembly is complete and diploid. Quantification of the orange/red, and black areas would be great too.
 ```
The numbers to estimate all the metrics you need are in the `-main.mx` file, one dimension is the copy number in the genome and the other dimension is the frequency in the reads.

Let me know if you need anything else.
Best
Gonza

**Comment by dcopetti** [comment]
Hi Gonza,

Thank you for the feedback, very helpful.
I am now running with more coverage (all R1 and half R2, should be about 22x at the het peak), k=31 and the updated memory requirements:
`kat comp -m 31 --disable_hash_grow -H 10000000000 -I 50000000000 -o PE1.5-Rab1 -t 6 PE700_1.5.fq genome_1.0.fa`
let's see if the result looks better. Will having less threads help with the memory? 

So a few more considerations about the histogram:
- the little orange (and >2x) reads between e.g. X-6 and X=25 are sequences that are duplicated in my genome: present twice in the assembly, but at freq similar to the unique sequences (heterozygous sites): these should be homozygous regions at single copy in each allele;
- Orange sequences (2x) between about X=25 and X=50 are sequences present twice in the assembly and at twice the frequency in the reads, so should be paralogous duplicated sequences;
- Black sequences between about X=6 and X=40 are not present in the assembly but from their frequency in the reads should be present in a single (~) copy in the diploid assembly, so are unassembled sequences.
Is it possible to estimate that black and orange fraction and extract the corresponding k-mers?

So I guess that the ideal assembly should have: a 0x distribution going quickly down to 0; a 1x distribution with 1 peak, hopefully no homo peak; a 2x (and >2x) distribution at the homo peak or higher. Would that be the right configuration?
Thanks,
Dario

**Comment by dcopetti** [comment]
Hi,
my test with more coverage and k-mer=31 gave me unexpected results: 
![pe1 5-rab1_31-main_spectra](https://user-images.githubusercontent.com/13842014/44577575-c6ab1f00-a791-11e8-9c68-4e5be8ea96e7.png)
the black area now has a peak at the het frequency and the amount of k-mers present twice in the assembly (orange bump in the previous histogram) almost disappeared.
The raw (all 150 bp, untrimmed but still of good quality) read coverage is about 32x of a 2n genome now. If I run the same read file with k=27, I get the same histogram as for k=31, so I wonder if one of the two input files has some issues and if one of the two results is wrong, for any reason.
Else, how to explain the discrepancy between the two? They would lead to pretty different conclusions I think.
Thanks in advance for any help,
Dario

**Comment by bjclavijo** [comment]
I would say, if I follow correctly, that the assembly is probably collapsing the haplotypes and you notice that more the more you grow k?

Stick to a small k (you can even lower it down to 21 if you want to start there) so you get less memory in errors, but put more coverage. At least 25x per haploid genome or 50x of the diploid. You do want to see clearly separated heterozygous and homozygous peaks.

If you’re going to use only a single read file, use R1, they have less errors and will then use less memory.

Best,

bj

**Comment by dcopetti** [comment]
I prepared a new reads input file, trimming below QV30 and clipping all reads at 240 nt:
![image](https://user-images.githubusercontent.com/13842014/44657576-97004f00-a9fd-11e8-9b7d-3f0a5c7a728c.png)
I have a 30x (of the haploid size) of this, they are all R1 of a PCR-free PE 470 bp library.
I run KAT as 
`kat comp -m 25 -H 10000000000 -o out -t 12 PE470_12.fq  genome_1.0.fa`
(also at k=23) and I still get a high haploid peak of non-reference k-mers:
![pe47012-rab1_25-main mx spectra-cn](https://user-images.githubusercontent.com/13842014/44657702-05dda800-a9fe-11e8-8670-0473adb52bc4.png)
this is way higher than the first plot I got here above.
That was made with R2 of a PRC-free PE 700 bp library, untrimmed and unclipped with reads at 151 nt.
I wonder what are the reasons for this inconsistency in the profiles of `kat comp`, if it is due to the read length, library type (?), or if it is so sensitive to changes in k-mer content between files.
Already with R1 and half of R2) of the PE700 I was seeing this high het blak peak.
Thank you in advance for your comments!

**Comment by bjclavijo** [comment]
Hi Dario,

    There is clearly more than one issue there, I am writing a tutorial on how to do k-mer spectra analyses like these since it is not very uncommon for people to get in the same pitfalls, if you send me an email next week I can send you a first draft of it. The spectra you're showing there in the last plot has a mode at 7x. You want the first mode to be ~20x at least to be able to differentiate peaks and such. so you want ~3 times more coverage than what you used. While read trimming/clipping may help to use include less errors in the distributions, you may find that it discards way too much coverage.

If you can use the reads as on the plot you've produced with the other tool where your heterozygous peak is ~40 you'll see the peaks more clearly. On the first spectra you sent the content recovery seemed better than on the other 2, are you sure you were using the same assembly and you have not filtered any content? If the last spectra are the right ones, your assembly may be collapsing both haplotypes heavily which, given that there are a lot of SNPs between the haplotypes, would lose a significant amount of content. The peak you're seeing on all your plots is the heterozygous one, which as you can see form the spectra with more coverage, is a lot of content. Make sure that you have not mistakenly activated the non-canonical counting on one of the hashes, since that could produce an erroneous result with a similar shape to that one (although I don't think this is what happened).



Best,

bj

**Comment by dcopetti** [comment]
Hi Bernardo,
I am now running kat comp with both PE700 files (so that reads do not overlap). Do the reads need to be of the exact length, also between files? Mine have been a bit trimmed at the source. In case I can clip them at 140 or so nt. 
I can't explain why we get so little coverage with the PE470 library, it is supposed to be >30x in the diploid peak. 
Just to make it clear for me, I am not using -C and -D, is that right? From the description it is not so clear which one is the default behavior.

**Comment by dcopetti** [comment]
Hi,
The run (`kat comp -m 23 -H 30000000000 -t12 -o out 'R1.fq R2.fq' 'genome.fa'`) completed with this plot:
![pe700both-rab1-main](https://user-images.githubusercontent.com/13842014/44844435-38301500-ac4b-11e8-9844-892436caa0a7.png)
The bulge of the 2x k-mers is visible now, but there are still lots of 0x k-mers. These should be unassembled and sequencing error k-mers, if I got it right. Is there a way to extract the sequences of the 0x k-mers above e.g. coverage 10x in the reads?
I am now running the same dataset with -C and -D.
Thanks

**Comment by bjclavijo** [comment]
Can you post or email de .mx and stats and output logs of the comps you executed? There is a couple of things we can check with that. I would very much like to compare the files from the first run to the files from the last run.

**Comment by dcopetti** [comment]
The files are here:
https://de.cyverse.org/dl/d/53E993BA-C0B4-4A84-8E25-DE4E69081D66/run_outputs.tar.gz
PE700-Rab1 is for the first run (only R2 of a PE700);
PE700both-Rab1 is for the run with both reads of PE700;
PE700both-Rab1C is for the run with both reads of PE700 with -C and -D, that looks very different:

![pe700both-rab1c-main](https://user-images.githubusercontent.com/13842014/45020621-c92e3400-b02f-11e8-9823-3a4fd749d1db.png)
probably what we really wanted to see. Maybe I did not report using the -C parameter at first? not sure though. From the documentation, it is not clear to me if e.g. -C counts both k-mers (with its RC) as one or as separate k-mers.

For this last run, the stdout was saying:
```
 success!
 success!
 done.  Time taken: 171.2s

Comparing hashes ... done.  Time taken: 895.1s

Merging results ... done.  Time taken: 1.8s

Saving results to disk ... done.  Time taken: 0.2s

Creating plot ...  Time taken: 0.8s

KAT COMP completed.
Total runtime: 5929.2s

Error: Couldn't open connection to gnuplot
```

**Comment by jonwright99** [comment]
Hi Dario,
As we briefly discussed last week, I think the problem here is whether you are using canonical kmers (generated from both strands) in the comp. With older KAT versions you had to use parameters -C and -D to specify that canonical kmers should be counted, ie. the default was to count non-canonical kmers. In later versions this has been reversed so the default is to use canonical kmers, ie. by not including the -C and -D parameters. We changed this as we generally always wanted to count canonical kmers. Can you check which version of KAT you're running and rerun the comp either including or not including -C and -D as appropriate.
Thanks,
Jon

**Comment by bjclavijo** [comment]
I am closing this as the issue seems to have been solved.

Best,

bj
