### ISSUE TITLE
kat filter seq does not take gzipped fastq files

### ISSUE THREAD

**Issue by aunderwo** [TGAC/KAT#123]
Whereas most KAT commands will take gzipped fastqs as input kast filter seq complainsof an unknown file extension

```
kat filter seq -m 21 --seq  16473_3#51_1.fastq.gz kat.filter.kmer-in.jf21
Kmer Analysis Toolkit (KAT) V2.4.1

Running KAT in filter sequence mode
-----------------------------------

Loading hashes into memory... done.  Time taken: 1.2s

Filtering sequences ...
  Time taken: 0.0s

KAT filter seq completed.
Total runtime: 1.2s

Error: Unknown file extension of 16473_3#51_1.fastq.gz
```

**Comment by maplesond** [comment]
Yes, this is a known limitation.  We use a different fastq parser for this part of KAT and haven't implemented gz processing as yet.  For the time being you'll need to workaround this by decompressing those files you wish to analyse via KAT sect.  As a rule of thumb any where you are kmer counting gz is supported, elsewhere it is not.

**Comment by aunderwo** [comment]
Thanks for the quick reply @maplesond 

Is this the same reason why process substitution won't work either as suggested here: https://kat.readthedocs.io/en/latest/faq.html

**Comment by maplesond** [comment]
The reason is that internally we use jellyfish2 for doing kmer counting.  That parsing code has been augmented to natively consume gzip compressed fasta/q files.  You can use process substitution here to consume bzip (or any other) compression instead.  However, with SECT we are using seqan to do fasta/q parsing.  The way the code is written it expects to load a file from disk not a stream, so process substitution or compression won't work the way it's currently setup.

**Comment by bjclavijo** [comment]
I don't think this will be fixed in KAT, and given it is a minor nuisance (the output from SECT is huge so having the original fasta file by comparison is not that bad) I will just close this issue.

Best,

bj
