### ISSUE TITLE
kat-sect-counts.cvg - terminal kmers missing

### ISSUE THREAD

**Issue by thackl** [TGAC/KAT#20]
Hi Dan,

I'm currently working with sects per sequence coverage count files and noticed that each record is 8 counts short at the end. I'm using a 19mer hash, I have not tested, if the number changes with other kmer sizes.

**Comment by maplesond** [comment]
Hi Thomas.  There should be set length - kmer +1 counts for each sequence.  So I can't explain why you have 9 short for 19 Mers.  Are you looking at the non zero kmer number?  Some kmers in a sequence may have a 0 count if they contain Ns or other non canonical bases.

**Comment by thackl** [comment]
Yeah,I was expecting length-kmer+1, that's how I noticed:

src | #
---|---
contig length | 1002
expected | 1002-19+1=984
kat sect | 976
jellyfish query -s contig hash.jf | 984

Terminal kmer coverage of .cvg/jellyfish -s
`.. 816 819 811 813 810 815 814`
`.. 816 819 811 813 810 815 814 812 812 885 886 890 891 891 1946`

The picture is consistent for all sequences, also I don't have 'N's in this contig set

**Comment by maplesond** [comment]
Hi Thomas,

That's a puzzle, I just tried this: "~/dev/KAT/src/kat sect -m 11 -o test_sect test.fa test.fa" with a fasta file containing this: 

>test1
TATAGCGCTATAGCGCTATAGCGCGCGCTATA

and I get the following results:

>test1
2 2 2 2 2 2 1 1 2 2 2 2 2 2 1 1 1 1 1 1 1 1

and 

seq_name        median  mean    gc%     seq_length      invalid_bases   %_invalid       non_zero_bases  %_non_zero      %_non_zero_corrected
test1   2       1.54545 0.50000 32      0       0.00000 22      100.00000       100.00000

So that's seq length of 32, with 22 non-zero bases.  i.e. len - kmer + 1, which corresponds with the count output.

Maybe this is something to do with the dataset or some other behaviour that's trickier to identify?  Could you post the exact command line you used?  Also could you try with the simple dataset I used and see if you can replicate the results?

Best regards,
Dan

**Comment by thackl** [comment]
I think I found the problem. I work with an previously created hashes:

`~/software/kat/bin/kat sect -m 11 -o test_sect_hash test.fa test.jf` works, but
`~/software/kat/bin/kat sect -o test_sect_hash test.fa test.jf` does not. 

Looks like sect defaults to a 27mer kmer size for computation instead of getting the size from the hash.

**Comment by maplesond** [comment]
Ok, thanks for pointing that out.  I'll look into getting a fix for this.

**Comment by maplesond** [comment]
I've implemented a fix at the top of the develop branch, if you would like to test it out before a new release is made: 3c744058ae1593d076e86a80b55de86a2e0d45c3

**Comment by maplesond** [comment]
Should be fixed in the latest release: https://github.com/TGAC/KAT/releases/tag/Release-2.1.0.  Please reopen if there are any issues.
