### ISSUE TITLE
Support for .fastq.gz files?

### ISSUE THREAD

**Issue by tseemann** [TGAC/KAT#37]
I thought SEQAN supported .gz streams?

```
% kat hist -t 72 -C -m 31 R1.fastq.gz
Kmer Analysis Toolkit (KAT) V2.0.8

Running KAT in HIST mode
------------------------

Input is a sequence file.  Counting kmers for Sa-R1.fastq.gz ...  Time taken: 0.1s

KAT HIST completed.
Total runtime: 0.1s

Error: Unsupported format
```

**Comment by maplesond** [comment]
SeqAN does.  In this case though it would be Jellyfish trying to consume the `.fastq.gz` file.  However, jellyfish should also support that format.  

There is something odd in your output though, you command line says `R1.fastq.gz` but the output contains: `Sa-R1.fastq.gz`.  I'm not sure how that's possible at the moment.  I'll take a closer look at this during the week.

**Comment by maplesond** [comment]
Hi Torsten, actually it appears jellyfish does not support .gz files directly (normal behaviour to work around this is to decompress using gzip and pipe into jellyfish.  This is going to get quite messy in the context of KAT.  I'll try to work out a way of doing this internally in C++ code for a future release.

**Comment by maplesond** [comment]
This is going to be quite difficult in the short term.  I'll look at this again in the future but I won't be able to implement anything for V2.1.  In the meantime, I'll make sure that an error is produced if a file with a .gz extension is passed in for a file to be counted.

**Comment by jennycraig** [comment]
LMAO...you guys are so PATHETIC..get a life bitches!

**Comment by johnomics** [comment]
Just got hit by this too, but named pipes work with `hist` at least:

```
mkfifo kat.fastq
gunzip -c R[12].fastq.gz > kat.fastq &
kat hist kat.fastq
```

Using KAT 2.2.0 test file `tests/data/ecoli_r1.1K.fastq`, I get exactly the same output with the original file, a pipe, and a pipe with KAT running multithreaded.

**Comment by maplesond** [comment]
Great workaround.  Thanks for this John!  I'll write this into the documentation for the next version.

**Comment by maplesond** [comment]
I've added this workaround into the documentation for the latest release.  Give the way KAT's interface works I don't think there's a better approach to dealing with this.  I'll keep this issue in mind for future releases but for now I'm going to close the case.

**Comment by tseemann** [comment]
@johnomics @maplesond you can probably do this use sub-shells as well?
```
kat hist <(gunzip -c file.fastq.gz) 
```

**Comment by johnomics** [comment]
Unfortunately not:

```
$ kat hist <(gunzip -c R1.fastq.gz) <(gunzip -c R2.fastq.gz)
Kmer Analysis Toolkit (KAT) V2.2.0

Running KAT in HIST mode
------------------------

KAT HIST completed.
Total runtime: 0.0s

src/input_handler.cc(69): Throw in function void kat::InputHandler::validateInput()
Dynamic exception type: boost::exception_detail::clone_impl<kat::InputFileException>
std::exception::what: std::exception
[kat::InputFileError*] = Could not find input file at: /proc/46203/fd/pipe:[76805967]; please check the path and try again.
```

Same result with a single input file.

**Comment by maplesond** [comment]
That's right, unfortunately the current code checks for file existence and doesn't support piping directly.  The named pipe works because it creates a temporary file.  Having said this, we could probably modify the code to support this method.  I think the main issue with sorting this problem out is that we currently support fastq and jellyfish hashes as input and distinguish them by the filename extension.  I'll reopen the case as a reminder to look into this for the next version.

**Comment by georgek** [comment]
Does the jellyfish hash file have a magic number that we can check instead of looking at the filename? I just had a quick look and can't see anything in the jellyfish docs about the file format. This would be a better way to do it. If it's not a jellyfish hash we can open it with the open function of libz which supports gzip and non-gzip content transparently (uses the gzip magic number to tell).

**Comment by maplesond** [comment]
Hi George,  I'll take another look at this.  I think it's not so straight forward as you suggest because we would want to integrate the decompression inside jellyfish to leverage it's multi-threaded reading.  I'll need to look into jellyfish's generator code and try to activate that if a gzip file is detected.

**Comment by maplesond** [comment]
Hi George, instead of modifying jellyfish I've modified the code to accept pipes from the command line.  So now we can say things like what @tseemann suggested above:

kat hist <(gunzip -c file.fastq.gz) 

In the more complicated case of "comp", you can still use pipes like you might expect:

kat comp <(gunzip -c file1.fastq.gz) <(gunzip -c file2.fastq.gz)

The changes are on the develop branch.  Can you test them out when you get a second and let me know if they work ok for you?
