### ISSUE TITLE
Compiling with a non-standard python3 location

### ISSUE THREAD

**Issue by vatese** [TGAC/KAT#41]
Is there a way to compile with a non-standard python location? I am using environment modules and it finds the python3 binary, but not the include or lib directories (consequently, configure fails as it is unable to find Python.h). I tried adding the variables CPPFLAGS, LIBS and LDFLAGS with no luck. Thanks in advance.

**Comment by maplesond** [comment]
Hi Miguel,

This might be due to your python installation.  Do you have a "dev" version installed, on linux (debian) systems you can install this to default location by typing "sudo apt-get install python3-dev".  This will include the headers and libraries that you need for compiling and running KAT with python support.  If you do this and have python installed to a standard location then you shouldn't need to worry about the environment variables you mention. My personal choice is to just install anaconda, this will have everything you need, header, libraries and a whole bunch of python packages.

Assuming you need python in a non-standard location, first make sure you have python.h and libpython3.so in your custom location in "include" and "lib" folders respectively.  At compile time set the CPPFLAGS to the include dir, LDFLAGS to the lib dir and that's probably enough.  To run you'll need to set the LD_LIBRARY_FLAGS to the lib dir as well.

I might look at supporting non-custom locations in the configuration system at some point in the future, for the time being the workaround above should work.

Hope that helps,

Best,
Dan

**Comment by maplesond** [comment]
Sorry, the runtime variable is LD_LIBRARY_PATH not LD_LIBRARY_FLAGS.

Best,
Dan

**Comment by vatese** [comment]
Thank you so much Daniel!

It worked when I removed the variable LIBS (I had it set to LIBS="-lpython3.5m"). I used:

export LDFLAGS="-L/home/python3/lib"
export CPPFLAGS="-I/home/python3/include/python3.5m"
export LIBS=''

Additionally the modulefile was incorrectly setting up LD_LIBRARY_PATH to /home/python3/lib/python3.5.

Cheers!
