### ISSUE TITLE
kat comp: Error: Parsing Command Line: too many positional options have been specified on the command line

### ISSUE THREAD

**Issue by mmokrejs** [TGAC/KAT#98]
```
kat comp -t 24 -n -o PE2016_vs_PE2017_MP2016_vs_MP2017 /scratch/work/project/bio/open-9-41/tt_16D1C3L12/paired_end_median_592bp__mean_601bp_201608//HKMHTBCXX.1.tt_16D1C3L12.trimmomatic.prinseq.minlen20.tadpole.k62.fasta \
  /scratch/work/project/bio/open-9-41/tt_16D1C3L12/paired_end_median_596bp__mean_587bp_201708//HT5V3BCXY.2.tt_16D1C3L12.trimmomatic.prinseq.minlen20.tadpole.k62.fasta \
  /scratch/work/project/bio/open-9-41/tt_16D1C3L12/mate_pairs_5kb:median_7321bp__mean_9525bp__8kb:median_7317bp__mean_9002bp_201608//HFYJ5AFXX.5kb.trimmomatic.fastq \
  /scratch/work/project/bio/open-9-41/tt_16D1C3L12/mate_pairs_5kb:median_7321bp__mean_9525bp__8kb:median_7317bp__mean_9002bp_201608//HFYJ5AFXX.5kb.trimmomatic.fastq \
  /scratch/work/project/bio/open-9-41/tt_16D1C3L12/mate_pairs_5kb:median_245bp__mean4126bp_201708/HWFNLBCXY.2.tt_16D1C3L12.trimmomatic.fastq
Kmer Analysis Toolkit (KAT) V2.4.2

Error: Parsing Command Line: too many positional options have been specified on the command line
```

I know, the paths are quire long and the `:` in dirnames are maybe nasty. Is the issue really about length or some other issue?

**Comment by maplesond** [comment]
So here the comp tool takes in 2 groups (or sometimes 3) of positional arguments.  In this case because there is nothing separating the groups it assumes each file belongs to a different group.  i.e. 5 groups, which KAT comp doesn't know what to do with.  I presume the intention is to treat the first 2 files as belonging to the assembly, and the next 3 to be the reads.  You should wrap the groups in double quotes, the KAT will essentially cat all the files in each group internally.  By the way, you should probably switch the groups so that reads are first and assembly is second to get the expected spectra-cn output. 

See here for an example:  https://kat.readthedocs.io/en/latest/using.html#comp

**Comment by maplesond** [comment]
Actually, looking at the docs has reminded me that we don't need to use process substitution for gzipped files any longer (still required if using bz2 though).  I'll adjust the docs accordingly.

**Comment by mmokrejs** [comment]
> So here the comp tool takes in 2 groups (or sometimes 3) of positional arguments

Aha, thank you, that I haven't realized. The documentation was too quick for me as a newbie. I thought I could at least prepare the all-against-all comparisons and later during plotting to specify what to plot against what.

Those were all reads. Fastq files were uncorrected reads and fasta files were after error-correction. I did not have handy variants of corrected reads of the latter.

Maybe try to an another example to the docs? While re-reading now the section 2.3 I think it would be helpful if you interleaved the text with `<input_1>`,  `<input_2>`, `<input_3>` to clarify where the stuff apears in the command line.

I will probably go for last three as one group. It is not an assembly but I wanted to see the diffs between the two PE libs and Nextera LMP preps (3 preps).

**Comment by maplesond** [comment]
Ah ok.  Yes, I just assumed as they had `tadpole` in the name and `fastq` as the extension that they were assemblies.  So in this case what you suggest is fine.  You probably want to add the `-n` option in this case to auto generate a density plot rather than a spectra cn plot.  Although, if you forget you can always just run `kat plot density ...` on the produced matrix file.
